### ISSUE TITLE
Implement minimum viable controller

### ISSUE THREAD

**Issue by gabikeane** [Pittsburgh-NEH-Institute/pr-app#4]
### Your to-do
- explore previous controllers (punch, etc)

### Additional context

**Comment by djbpitt** [comment]
@gabikeane Just to keep you in the loop:

Apparently I never implemented a controller for our Institute materials earlier, but I did write up the theory and some implementation documentation in the *gh-pages* branch of our 2020 Institute repo in the *eXist-db-stages* subdirectory. See:

* [Query-rewriting theory](https://github.com/Pittsburgh-NEH-Institute/Institute-Materials-2020/blob/gh-pages/eXist-db-stages/neh_05_query-rewriting_theory.md)
* [Reading TEI](https://github.com/Pittsburgh-NEH-Institute/Institute-Materials-2020/blob/gh-pages/eXist-db-stages/neh_06_reading_tei.md)
* [Creating a reading view in HTML](https://github.com/Pittsburgh-NEH-Institute/Institute-Materials-2020/blob/gh-pages/eXist-db-stages/neh_07_view-tei.md)

I'll review these and come to our next meeting prepared to discuss, and, if we have texts ready, to begin to implement. If I do any coding in this direction, I'll do it in a feature branch and let you know, through a pull request, when it's ready for review.

**Comment by djbpitt** [comment]
@djbpitt Controller should return, through pipeline, list of article titles in response to URI _http://(path-to-app)/guide/titles_.

Options after _guide_ are based on _articlesguide.png_ in wireframe directory.

1. Move TEI-to-HTML typeswitch code into library.
2. Verify modules/wrapper.xql
3. Stitch together

API includes mapping from URIs to system resources (duh). But we may want to include direct access to resources that aren't part of the app interface as we envision it. Ponder … (@gabikeane)

**Comment by djbpitt** [comment]
# Minimum viable controller creates titles list

## Issues

### Output of *titles.xql*

Currently pseudo-HTML, with html element names, but in no namespace. Use `hoax:` or `local:` instead? If we use something like `hoax:section` as element name, will it clash with `hoax:section` as helper function name in `typeswitch`? 

If only views will be full raw TEI of entire file and HTML, using HTML names in no namespace for local purposes is probably safe, but is it potentially confusing?

### _hoax-to-html.xql_

Should `typeswitch` be inside function library imported into view file, instead of directly inside view file? Perhaps not, because mapping from model to HTML output may vary depending on chosen view. Or will it?

### wrapper.xql

Separate into smaller parts (e.g., contents of `<head>`, header, navigation, footer) and import for greater legibility?
